[[language]]
name = "html"
auto-format = false

[[language]]
name = "python"
indent = { tab-width = 4, unit = "\t" }

roots = ["pyproject.toml", "."]
file-types = ["py", "pyi"]
auto-format = true

formatter = { command = "black", args = ["--quiet", "-"] }
language-servers = [
  { name = "ruff", only-features = [
    "format",
    "workspace-command",
    "code-action",
    "diagnostics",
  ] },
  "pyright",
]

[[language]]
name = "toml"
auto-format = true

# [language-server.pylsp.config.pylsp.plugins.flake8]
# enabled = false
# ignore = ["E501"]

# [language-server.pylsp.config.pylsp.plugins.autopep8]
# enabled = false

# [language-server.pylsp.config.pylsp.plugins.pyflakes]
# enabled = false

# [language-server.pylsp.config.pylsp.plugins.pycodestyle]
# enabled = false


[language-server.taplo]
config = {}

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config.initializationOptions]
command = [
  "golangci-lint",
  "run",
  "--out-format",
  "json",
  "--issues-exit-code=1",
]

[language-server.pyright]
timeout = 100
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
autoImportCompletions = true
autoSearchPaths = true
diagnosticMode = "openFilesOnly"
useLibraryCodeForTypes = true

[language-server.ruff]
timeout = 100
command = "ruff-lsp"

[[language]]
name = "hcl"
language-servers = ["terraform-ls"]
auto-format = true
formatter = { command = "teraform", args = [
  "fmt",
  "-recursive",
  "&&",
  "lintlint",
  "-a",
] }
